# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'DDMEventBusExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  pod 'DDMEventBus', :path => '../'

  target 'DDMEventBusExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDMEventBusExampleUITests' do
    # Pods for testing
  end

end
